
import java.awt.Toolkit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Buddika
 */
public class GUI2 extends javax.swing.JFrame {

    /**
     * Creates new form GUI2
     */
    public GUI2() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(
                ("C:\\Users\\Buddika\\Documents\\NetBeansProjects\\bill\\src\\U2ntitled-1.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        link = new javax.swing.JLabel();
        hover = new javax.swing.JLabel();
        T = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Translator Natzi v2.0");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jTextArea2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextArea2MouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 80));

        jScrollPane2.setBorder(null);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextArea1MouseMoved(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, 430, 50));

        link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkMouseClicked(evt);
            }
        });
        link.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                linkMouseMoved(evt);
            }
        });
        getContentPane().add(link, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 170, 30));

        hover.setBackground(new java.awt.Color(15, 54, 98));
        hover.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 14)); // NOI18N
        hover.setForeground(new java.awt.Color(204, 204, 204));
        hover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hover.setOpaque(true);
        hover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hoverMouseMoved(evt);
            }
        });
        getContentPane().add(hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 550, 20));

        T.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TMouseClicked(evt);
            }
        });
        T.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                TMouseMoved(evt);
            }
        });
        getContentPane().add(T, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 65, 50, 50));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gonewGUI2.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 230));

        jMenuBar1.setToolTipText("");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("Manual");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator1);

        jMenuItem3.setText("Developers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMouseClicked
String s = jTextArea1.getText();
       char arr[] = s.toCharArray();
       for(int i=0; i<arr.length;i++){
           
           
           if(s.charAt(i)=='a'){
               jTextArea2.setText(jTextArea2.getText()+"1.");                                   
           }
           else if(s.charAt(i)=='b'){
                jTextArea2.setText(jTextArea2.getText()+"2."); 
           }
           else if(s.charAt(i)=='c'){
                jTextArea2.setText(jTextArea2.getText()+"3."); 
           }
           else if(s.charAt(i)=='d'){
                jTextArea2.setText(jTextArea2.getText()+"4."); 
           }
           else if(s.charAt(i)=='e'){
                jTextArea2.setText(jTextArea2.getText()+"5."); 
           }
           else if(s.charAt(i)=='f'){
                jTextArea2.setText(jTextArea2.getText()+"6."); 
           }
           else if(s.charAt(i)=='g'){
                jTextArea2.setText(jTextArea2.getText()+"7."); 
           }
           else if(s.charAt(i)=='h'){
                jTextArea2.setText(jTextArea2.getText()+"8."); 
           }
           else if(s.charAt(i)=='i'){
                jTextArea2.setText(jTextArea2.getText()+"9."); 
           }
           else if(s.charAt(i)=='j'){
                jTextArea2.setText(jTextArea2.getText()+"10."); 
           }
           else if(s.charAt(i)=='k'){
                jTextArea2.setText(jTextArea2.getText()+"11."); 
           }
           else if(s.charAt(i)=='l'){
                jTextArea2.setText(jTextArea2.getText()+"12."); 
           }
           else if(s.charAt(i)=='m'){
                jTextArea2.setText(jTextArea2.getText()+"13."); 
           }
           else if(s.charAt(i)=='n'){
                jTextArea2.setText(jTextArea2.getText()+"14."); 
           }
           else if(s.charAt(i)=='o'){
                jTextArea2.setText(jTextArea2.getText()+"15."); 
           }
           else if(s.charAt(i)=='p'){
                jTextArea2.setText(jTextArea2.getText()+"16."); 
           }
           else if(s.charAt(i)=='q'){
                jTextArea2.setText(jTextArea2.getText()+"17."); 
           }
           else if(s.charAt(i)=='r'){
                jTextArea2.setText(jTextArea2.getText()+"18."); 
           }
           else if(s.charAt(i)=='s'){
                jTextArea2.setText(jTextArea2.getText()+"19."); 
           }
           else if(s.charAt(i)=='t'){
                jTextArea2.setText(jTextArea2.getText()+"20."); 
           }
           else if(s.charAt(i)=='u'){
                jTextArea2.setText(jTextArea2.getText()+"21."); 
           }
           else if(s.charAt(i)=='v'){
                jTextArea2.setText(jTextArea2.getText()+"22."); 
           }
           else if(s.charAt(i)=='w'){
                jTextArea2.setText(jTextArea2.getText()+"23."); 
           }
           else if(s.charAt(i)=='x'){
                jTextArea2.setText(jTextArea2.getText()+"24."); 
           }
           else if(s.charAt(i)=='y'){
                jTextArea2.setText(jTextArea2.getText()+"25."); 
           }
           else if(s.charAt(i)=='z'){
                jTextArea2.setText(jTextArea2.getText()+"26."); 
           }
           else if(s.charAt(i)==' '){
                jTextArea2.setText(jTextArea2.getText()+"0."); 
           }
           else{
               hover.setText("Wrong input type");
           
               
           }

          
           }
    }//GEN-LAST:event_TMouseClicked

    private void linkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMouseClicked
new tranlat().setVisible(true);
this.dispose();
    }//GEN-LAST:event_linkMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new ManualGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new developersGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void hoverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverMouseMoved
        // TODO add  handling code here:
    }//GEN-LAST:event_hoverMouseMoved

    private void jTextArea1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseMoved
hover.setText("Enter your message to translate");
        
    }//GEN-LAST:event_jTextArea1MouseMoved

    private void jTextArea2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea2MouseMoved
hover.setText("It shows, your translated message");
    }//GEN-LAST:event_jTextArea2MouseMoved

    private void TMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMouseMoved
hover.setText("Translate it");
    }//GEN-LAST:event_TMouseMoved

    private void linkMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMouseMoved
hover.setText("Switch, Codes ----> Words");
    }//GEN-LAST:event_linkMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel T;
    private javax.swing.JLabel hover;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel link;
    // End of variables declaration//GEN-END:variables
}
