
import java.awt.Toolkit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Buddika
 */
public class tranlat extends javax.swing.JFrame {

    public tranlat() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(
                ("C:\\Users\\Buddika\\Documents\\NetBeansProjects\\bill\\src\\U2ntitled-1.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        link = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hover = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Translator Natzi v2.0");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jTextArea2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextArea2MouseMoved(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 131, 490, 80));

        jScrollPane1.setBorder(null);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextArea1MouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 66, 430, 50));

        link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkMouseClicked(evt);
            }
        });
        link.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                linkMouseMoved(evt);
            }
        });
        getContentPane().add(link, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 170, 30));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 64, 50, 50));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 90, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gonewGUI1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 230));

        hover.setBackground(new java.awt.Color(15, 54, 98));
        hover.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 14)); // NOI18N
        hover.setForeground(new java.awt.Color(204, 204, 204));
        hover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hover.setOpaque(true);
        hover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hoverMouseMoved(evt);
            }
        });
        getContentPane().add(hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 550, 20));

        jMenuBar1.setToolTipText("");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("Manual");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator1);

        jMenuItem3.setText("Developers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new developersGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new ManualGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void linkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMouseClicked
        new GUI2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_linkMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
String s = jTextArea1.getText();
        String[] arr = s.split("\\.");
        for (int i = 0; i < arr.length; i++) {
            switch (arr[i]) {
                case "1":
                jTextArea2.setText(jTextArea2.getText() + "a");
                break;
                case "2":
                jTextArea2.setText(jTextArea2.getText() + "b");
                break;
                case "3":
                jTextArea2.setText(jTextArea2.getText() + "c");
                break;

                case "4":
                jTextArea2.setText(jTextArea2.getText() + "d");
                break;
                case "5":
                jTextArea2.setText(jTextArea2.getText() + "e");
                break;
                case "6":
                jTextArea2.setText(jTextArea2.getText() + "f");
                break;
                case "7":
                jTextArea2.setText(jTextArea2.getText() + "g");
                break;
                case "8":
                jTextArea2.setText(jTextArea2.getText() + "h");
                break;
                case "9":
                jTextArea2.setText(jTextArea2.getText() + "i");
                break;
                case "10":
                jTextArea2.setText(jTextArea2.getText() + "j");
                break;
                case "11":
                jTextArea2.setText(jTextArea2.getText() + "k");
                break;
                case "12":
                jTextArea2.setText(jTextArea2.getText() + "l");
                break;
                case "13":
                jTextArea2.setText(jTextArea2.getText() + "m");
                break;
                case "14":
                jTextArea2.setText(jTextArea2.getText() + "n");
                break;
                case "15":
                jTextArea2.setText(jTextArea2.getText() + "o");
                break;
                case "16":
                jTextArea2.setText(jTextArea2.getText() + "p");
                break;
                case "17":
                jTextArea2.setText(jTextArea2.getText() + "q");
                break;
                case "18":
                jTextArea2.setText(jTextArea2.getText() + "r");
                break;

                case "19":
                jTextArea2.setText(jTextArea2.getText() + "s");
                break;
                case "20":
                jTextArea2.setText(jTextArea2.getText() + "t");
                break;
                case "21":
                jTextArea2.setText(jTextArea2.getText() + "u");
                break;
                case "22":
                jTextArea2.setText(jTextArea2.getText() + "v");
                break;
                case "23":
                jTextArea2.setText(jTextArea2.getText() + "w");
                break;
                case "24":
                jTextArea2.setText(jTextArea2.getText() + "x");
                break;
                case "25":
                jTextArea2.setText(jTextArea2.getText() + "y");
                break;
                case "26":
                jTextArea2.setText(jTextArea2.getText() + "z");
                break;
                case "0":
                jTextArea2.setText(jTextArea2.getText() + " ");
                break;

            }
            

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void hoverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverMouseMoved
        // TODO add  handling code here:
    }//GEN-LAST:event_hoverMouseMoved

    private void jTextArea1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseMoved
hover.setText("Enter the codes");
    }//GEN-LAST:event_jTextArea1MouseMoved

    private void jTextArea2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea2MouseMoved
hover.setText("It shows, the message");
    }//GEN-LAST:event_jTextArea2MouseMoved

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
hover.setText("show it");
    }//GEN-LAST:event_jLabel3MouseMoved

    private void linkMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMouseMoved
hover.setText("Switch, Words ----> Codes");
    }//GEN-LAST:event_linkMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tranlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tranlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tranlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tranlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new tranlat().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel link;
    // End of variables declaration//GEN-END:variables
}
